/* ═══════════════════════════════════════════════════════════════════════
   MicroChain Admin — app.js
   Interact with UniversityRegistry + CredentialSchema contracts via MetaMask
   ═══════════════════════════════════════════════════════════════════════ */

// ── Embedded ABIs (generated by `npx hardhat compile`) ─────────────────

const REGISTRY_ABI = [
    { "inputs": [], "stateMutability": "nonpayable", "type": "constructor" },
    { "inputs": [{ "internalType": "address", "name": "owner", "type": "address" }], "name": "OwnableInvalidOwner", "type": "error" },
    { "inputs": [{ "internalType": "address", "name": "account", "type": "address" }], "name": "OwnableUnauthorizedAccount", "type": "error" },
    { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "university", "type": "address" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "UniversityAuthorized", "type": "event" },
    { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "university", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "UniversityRevoked", "type": "event" },
    { "inputs": [], "name": "activeUniversityCount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
    { "inputs": [{ "internalType": "address", "name": "_university", "type": "address" }, { "internalType": "string", "name": "_name", "type": "string" }], "name": "authorizeUniversity", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [], "name": "getAllUniversityAddresses", "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }], "stateMutability": "view", "type": "function" },
    { "inputs": [{ "internalType": "address", "name": "_university", "type": "address" }], "name": "getUniversity", "outputs": [{ "components": [{ "internalType": "string", "name": "name", "type": "string" }, { "internalType": "address", "name": "addr", "type": "address" }, { "internalType": "uint256", "name": "authorizedAt", "type": "uint256" }, { "internalType": "bool", "name": "isActive", "type": "bool" }], "internalType": "struct UniversityRegistry.University", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" },
    { "inputs": [{ "internalType": "address", "name": "_university", "type": "address" }], "name": "isAuthorizedUniversity", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
    { "inputs": [], "name": "owner", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
    { "inputs": [{ "internalType": "address", "name": "_university", "type": "address" }], "name": "revokeUniversity", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [], "name": "totalRegisteredUniversities", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }
];

const SCHEMA_ABI = [
    { "inputs": [{ "internalType": "address", "name": "_registry", "type": "address" }], "stateMutability": "nonpayable", "type": "constructor" },
    { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "schemaId", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }, { "indexed": false, "internalType": "string", "name": "schemaCode", "type": "string" }, { "indexed": true, "internalType": "address", "name": "creator", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "SchemaCreated", "type": "event" },
    { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "schemaId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "by", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "SchemaDeactivated", "type": "event" },
    { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_schemaCode", "type": "string" }], "name": "createSchema", "outputs": [{ "internalType": "uint256", "name": "schemaId", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [{ "internalType": "uint256", "name": "_schemaId", "type": "uint256" }], "name": "deactivateSchema", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [], "name": "getAllSchemaIds", "outputs": [{ "internalType": "uint256[]", "name": "", "type": "uint256[]" }], "stateMutability": "view", "type": "function" },
    { "inputs": [{ "internalType": "uint256", "name": "_schemaId", "type": "uint256" }], "name": "getSchema", "outputs": [{ "components": [{ "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "schemaCode", "type": "string" }, { "internalType": "address", "name": "creator", "type": "address" }, { "internalType": "uint256", "name": "createdAt", "type": "uint256" }, { "internalType": "bool", "name": "isActive", "type": "bool" }], "internalType": "struct CredentialSchema.Schema", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" },
    { "inputs": [{ "internalType": "uint256", "name": "_schemaId", "type": "uint256" }], "name": "isActiveSchema", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
    { "inputs": [], "name": "registry", "outputs": [{ "internalType": "contract UniversityRegistry", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
    { "inputs": [], "name": "totalSchemas", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }
];

// ── Hardhat local RPC (direct connection, bypasses MetaMask cache) ──────

const HARDHAT_RPC_URL = 'http://127.0.0.1:8545';

// ── App state ───────────────────────────────────────────────────────────

const state = {
    provider: null,       // MetaMask BrowserProvider (for signing txs)
    readProvider: null,   // Direct JsonRpcProvider (for read-only calls)
    signer: null,
    account: null,
    registry: null,       // write contract (connected to signer)
    schema: null,         // write contract (connected to signer)
    registryRead: null,   // read-only contract (direct RPC, no MetaMask)
    schemaRead: null,     // read-only contract (direct RPC, no MetaMask)
    owner: null,
    isOwner: false,
    isUni: false,
};

// ── DOM helpers ─────────────────────────────────────────────────────────

const $ = (id) => document.getElementById(id);
const q = (sel) => document.querySelector(sel);
const qa = (sel) => [...document.querySelectorAll(sel)];

// ── Toast notifications ─────────────────────────────────────────────────

function toast(msg, type = 'info', duration = 5000) {
    const container = $('toast-container');
    const el = document.createElement('div');
    el.className = `toast ${type}`;
    el.textContent = msg;
    el.onclick = () => el.remove();
    container.appendChild(el);
    setTimeout(() => el.remove(), duration);
}

function txToast(hash) {
    const container = $('toast-container');
    const el = document.createElement('div');
    el.className = 'toast success';
    el.innerHTML = `✓ Transaction confirmed<br><span class="tx-hash">${hash}</span>`;
    el.onclick = () => el.remove();
    container.appendChild(el);
    setTimeout(() => el.remove(), 8000);
}

// ── Button loading state ────────────────────────────────────────────────

function setLoading(btn, loading) {
    if (loading) {
        btn.classList.add('loading');
        btn.disabled = true;
    } else {
        btn.classList.remove('loading');
        btn.disabled = false;
    }
}

// ── Error message extractor ─────────────────────────────────────────────

function friendlyError(err) {
    // Solidity require() message
    const match = err?.message?.match(/reverted with reason string '(.+?)'/);
    if (match) return match[1];
    if (err?.reason) return err.reason;
    if (err?.message?.includes('user rejected')) return 'Transaction rejected by user.';
    if (err?.message?.includes('insufficient funds')) return 'Insufficient funds for gas.';
    return err?.message?.split('\n')[0] ?? 'Unknown error';
}

// ── Utility ─────────────────────────────────────────────────────────────

function shortAddr(addr) {
    return addr ? `${addr.slice(0, 6)}…${addr.slice(-4)}` : '';
}

function formatDate(timestamp) {
    if (!timestamp || timestamp === 0n) return '—';
    return new Date(Number(timestamp) * 1000).toLocaleDateString('it-IT', {
        day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit'
    });
}

// ── Wallet connection ───────────────────────────────────────────────────

async function connectWallet() {
    if (!window.ethereum) {
        toast('MetaMask not found. Please install it from metamask.io', 'error', 8000);
        return;
    }
    try {
        await window.ethereum.request({ method: 'eth_requestAccounts' });
        state.provider = new ethers.BrowserProvider(window.ethereum);
        state.signer = await state.provider.getSigner();
        state.account = await state.signer.getAddress();

        $('wallet-chip').classList.add('visible');
        $('wallet-addr').textContent = shortAddr(state.account);
        $('connect-btn').style.display = 'none';

        // Try to load contracts if addresses are already set
        await tryLoadContracts();

        // Hide main connect prompt if visible
        $('connect-prompt').style.display = 'none';

        toast('Wallet connected successfully!', 'success');
    } catch (err) {
        toast(friendlyError(err), 'error');
    }
}

// ── Load contracts from address inputs ─────────────────────────────────
// We create TWO providers:
//   readProvider  = direct JsonRpcProvider → bypasses MetaMask cache entirely
//   signer        = MetaMask BrowserProvider → used only for signing txs

async function tryLoadContracts() {
    const regAddr = $('registry-addr').value.trim();
    const schemaAddr = $('schema-addr').value.trim();

    console.group('🔍 tryLoadContracts — DIAGNOSTIC');
    console.log('1. Registry address from input:', regAddr);
    console.log('2. Schema address from input:  ', schemaAddr);
    console.log('3. Signer present?', !!state.signer);
    console.log('4. Connected account:', state.account);
    console.log('5. HARDHAT_RPC_URL:', HARDHAT_RPC_URL);

    if (!state.signer) { console.warn('❌ No signer — aborting'); console.groupEnd(); return; }
    if (!ethers.isAddress(regAddr)) { console.warn('❌ Registry address is not valid'); console.groupEnd(); return; }
    if (!ethers.isAddress(schemaAddr)) { console.warn('❌ Schema address is not valid'); console.groupEnd(); return; }

    try {
        // ── Step A: Check what MetaMask sees ──
        console.log('\n── Step A: MetaMask network info ──');
        const mmNetwork = await state.provider.getNetwork();
        console.log('MetaMask chainId:', mmNetwork.chainId.toString());
        console.log('MetaMask network name:', mmNetwork.name);

        // ── Step B: Check MetaMask eth_getCode ──
        console.log('\n── Step B: eth_getCode via MetaMask (BrowserProvider) ──');
        const mmCode = await state.provider.getCode(regAddr);
        console.log('Code length via MetaMask:', mmCode.length, 'chars');
        console.log('Is 0x (empty)?', mmCode === '0x');
        if (mmCode === '0x') {
            console.error('⚠️  MetaMask sees NO code at', regAddr, '— this is the bug!');
            console.log('   MetaMask is probably caching stale state or on the wrong network.');
        }

        // ── Step C: Direct RPC provider ──
        console.log('\n── Step C: Direct JsonRpcProvider to', HARDHAT_RPC_URL, '──');
        state.readProvider = new ethers.JsonRpcProvider(HARDHAT_RPC_URL);
        const directNetwork = await state.readProvider.getNetwork();
        console.log('Direct RPC chainId:', directNetwork.chainId.toString());

        const directCode = await state.readProvider.getCode(regAddr);
        console.log('Code length via direct RPC:', directCode.length, 'chars');
        console.log('Is 0x (empty)?', directCode === '0x');
        if (directCode === '0x') {
            console.error('⚠️  Even direct RPC sees no contract. Did you run the deploy script?');
            toast('No contract found at ' + regAddr + '. Have you deployed?', 'error');
            console.groupEnd();
            return;
        }

        // ── Step D: Create contracts ──
        console.log('\n── Step D: Creating contract instances ──');
        state.registryRead = new ethers.Contract(regAddr, REGISTRY_ABI, state.readProvider);
        state.schemaRead = new ethers.Contract(schemaAddr, SCHEMA_ABI, state.readProvider);
        state.registry = new ethers.Contract(regAddr, REGISTRY_ABI, state.signer);
        state.schema = new ethers.Contract(schemaAddr, SCHEMA_ABI, state.signer);
        console.log('✓ Contracts created (read + write)');

        // ── Step E: Call owner() ──
        console.log('\n── Step E: Calling owner() via direct RPC ──');
        state.owner = await state.registryRead.owner();
        console.log('Contract owner address:', state.owner);
        console.log('Connected account:     ', state.account);
        console.log('Are they equal?', state.account?.toLowerCase() === state.owner?.toLowerCase());
        state.isOwner = state.account?.toLowerCase() === state.owner?.toLowerCase();

        // ── Step F: Check if university ──
        console.log('\n── Step F: isAuthorizedUniversity() ──');
        state.isUni = await state.registryRead.isAuthorizedUniversity(state.account);
        console.log('Is authorized university?', state.isUni);

        console.log('\n✅ ALL CHECKS PASSED — loading UI');
        console.groupEnd();

        updateRoleBadge();
        showApp();
        await refreshAll();
    } catch (err) {
        console.error('\n❌ FAILED at some step. Full error:');
        console.error(err);
        console.log('Error code:', err?.code);
        console.log('Error reason:', err?.reason);
        console.log('Error data:', err?.data);
        console.log('Error info:', err?.info);
        console.groupEnd();
        toast('Could not connect to contracts: ' + friendlyError(err), 'error');
    }
}

function updateRoleBadge() {
    const badge = $('role-badge');
    badge.style.display = 'inline-block';
    if (state.isOwner) {
        badge.className = 'role-badge owner';
        badge.textContent = '👑 Owner';
    } else if (state.isUni) {
        badge.className = 'role-badge university';
        badge.textContent = '🎓 University';
    } else {
        badge.className = 'role-badge guest';
        badge.textContent = 'Guest';
    }
}

function showApp() {
    $('app').style.display = 'block';
    $('setup-panel').style.display = 'none';
}

// ── Tab switching ───────────────────────────────────────────────────────

function initTabs() {
    qa('.tab-btn').forEach(btn => {
        btn.onclick = () => {
            qa('.tab-btn').forEach(b => b.classList.remove('active'));
            qa('.tab-panel').forEach(p => p.classList.remove('active'));
            btn.classList.add('active');
            $(`panel-${btn.dataset.tab}`).classList.add('active');
        };
    });
}

// ══════════════════════════════════════════════════════════════════════
//  OWNER ACTIONS
// ══════════════════════════════════════════════════════════════════════

async function authorizeUniversity() {
    const addr = $('auth-addr').value.trim();
    const name = $('auth-name').value.trim();
    const btn = $('btn-authorize');

    if (!ethers.isAddress(addr)) { toast('Invalid Ethereum address', 'warning'); return; }
    if (!name) { toast('University name is required', 'warning'); return; }

    setLoading(btn, true);
    try {
        const tx = await state.registry.authorizeUniversity(addr, name);
        toast('Transaction sent — waiting for confirmation…', 'info');
        const receipt = await tx.wait();
        txToast(receipt.hash);
        $('auth-addr').value = '';
        $('auth-name').value = '';
        await refreshUniversities();
        // Re-detect own role (e.g. owner authorized their own address)
        state.isUni = await state.registryRead.isAuthorizedUniversity(state.account);
        updateRoleBadge();
    } catch (err) {
        toast(friendlyError(err), 'error');
    } finally {
        setLoading(btn, false);
    }
}

async function revokeUniversity(addr) {
    if (!confirm(`Revoke authorization for\n${addr}?`)) return;
    const btn = $(`revoke-${addr}`);
    if (btn) setLoading(btn, true);
    try {
        const tx = await state.registry.revokeUniversity(addr);
        toast('Transaction sent — waiting for confirmation…', 'info');
        const receipt = await tx.wait();
        txToast(receipt.hash);
        await refreshUniversities();
        state.isUni = await state.registryRead.isAuthorizedUniversity(state.account);
        updateRoleBadge();
    } catch (err) {
        toast(friendlyError(err), 'error');
    } finally {
        if (btn) setLoading(btn, false);
    }
}

// ══════════════════════════════════════════════════════════════════════
//  UNIVERSITY ACTIONS
// ══════════════════════════════════════════════════════════════════════

async function createSchema() {
    const name = $('schema-name').value.trim();
    const code = $('schema-code').value.trim().toUpperCase();
    const btn = $('btn-create-schema');

    if (!name) { toast('Credential name is required', 'warning'); return; }
    if (!code) { toast('Short code is required', 'warning'); return; }

    setLoading(btn, true);
    try {
        const tx = await state.schema.createSchema(name, code);
        toast('Transaction sent — waiting for confirmation…', 'info');
        const receipt = await tx.wait();
        txToast(receipt.hash);
        $('schema-name').value = '';
        $('schema-code').value = '';
        await refreshSchemas();
    } catch (err) {
        toast(friendlyError(err), 'error');
    } finally {
        setLoading(btn, false);
    }
}

async function deactivateSchema(id) {
    if (!confirm(`Deactivate credential schema #${id}?`)) return;
    const btn = $(`deactivate-${id}`);
    if (btn) setLoading(btn, true);
    try {
        const tx = await state.schema.deactivateSchema(id);
        toast('Transaction sent — waiting for confirmation…', 'info');
        const receipt = await tx.wait();
        txToast(receipt.hash);
        await refreshSchemas();
    } catch (err) {
        toast(friendlyError(err), 'error');
    } finally {
        if (btn) setLoading(btn, false);
    }
}

// ══════════════════════════════════════════════════════════════════════
//  DATA REFRESH
// ══════════════════════════════════════════════════════════════════════

async function refreshAll() {
    await Promise.all([refreshUniversities(), refreshSchemas()]);
}

async function refreshUniversities() {
    const list = $('uni-list');
    list.innerHTML = '<div class="empty-state"><span class="icon">⏳</span>Loading…</div>';

    try {
        const addresses = await state.registryRead.getAllUniversityAddresses();
        const unis = await Promise.all(addresses.map(a => state.registryRead.getUniversity(a)));

        $('uni-count').textContent = unis.filter(u => u.isActive).length;

        if (unis.length === 0) {
            list.innerHTML = '<div class="empty-state"><span class="icon">🏛️</span>No universities registered yet.</div>';
            return;
        }

        list.innerHTML = '';
        unis.forEach((uni, i) => {
            const addr = addresses[i];
            const isMe = addr.toLowerCase() === state.account?.toLowerCase();
            const card = document.createElement('div');
            card.className = 'entity-card';
            card.innerHTML = `
        <div class="status-dot ${uni.isActive ? 'active' : 'revoked'}"></div>
        <div class="entity-info">
          <div class="entity-name">${escapeHtml(uni.name) || '(no name)'}${isMe ? ' <span style="color:#a78bfa;font-size:11px;">• you</span>' : ''}</div>
          <div class="entity-addr">${addr}</div>
          <div class="entity-meta">${uni.isActive ? '✅ Active' : '❌ Revoked'} · Authorized ${formatDate(uni.authorizedAt)}</div>
        </div>
        ${state.isOwner && uni.isActive ? `
          <button class="btn btn-danger"
                  id="revoke-${addr}"
                  onclick="revokeUniversity('${addr}')">
            <span class="spinner"></span>
            <span class="btn-label">Revoke</span>
          </button>` : ''}
      `;
            list.appendChild(card);
        });
    } catch (err) {
        list.innerHTML = `<div class="empty-state">Error loading data: ${escapeHtml(friendlyError(err))}</div>`;
    }
}

async function refreshSchemas() {
    const list = $('schema-list');
    list.innerHTML = '<div class="empty-state"><span class="icon">⏳</span>Loading…</div>';

    try {
        const ids = await state.schemaRead.getAllSchemaIds();
        const schemas = await Promise.all(ids.map(id => state.schemaRead.getSchema(id)));

        $('schema-count').textContent = schemas.filter(s => s.isActive).length;

        if (schemas.length === 0) {
            list.innerHTML = '<div class="empty-state"><span class="icon">📋</span>No credential types defined yet.</div>';
            return;
        }

        list.innerHTML = '';
        schemas.forEach((s) => {
            const card = document.createElement('div');
            card.className = 'entity-card';

            const canDeactivate = state.isUni && s.isActive;

            card.innerHTML = `
        <div class="status-dot ${s.isActive ? 'active' : 'revoked'}"></div>
        <div class="entity-info">
          <div class="entity-name">${escapeHtml(s.name)} <span style="color:#7c5cfc;font-size:11px;font-family:'JetBrains Mono',monospace;">[${escapeHtml(s.schemaCode)}]</span></div>
          <div class="entity-addr">Schema ID: #${s.id} · Creator: ${shortAddr(s.creator)}</div>
          <div class="entity-meta">${s.isActive ? '✅ Active' : '❌ Deactivated'} · Created ${formatDate(s.createdAt)}</div>
        </div>
        ${canDeactivate ? `
          <button class="btn btn-danger"
                  id="deactivate-${s.id}"
                  onclick="deactivateSchema(${s.id})">
            <span class="spinner"></span>
            <span class="btn-label">Deactivate</span>
          </button>` : ''}
      `;
            list.appendChild(card);
        });
    } catch (err) {
        list.innerHTML = `<div class="empty-state">Error loading data: ${escapeHtml(friendlyError(err))}</div>`;
    }
}

// ── XSS prevention ──────────────────────────────────────────────────────

function escapeHtml(str) {
    return String(str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ── Try to auto-load config from Ignition or deploy-config.json ────────

async function tryLoadConfig() {
    // Source 1: Hardhat Ignition output (what `npx hardhat ignition deploy` writes)
    try {
        const res = await fetch('../ignition/deployments/chain-31337/deployed_addresses.json');
        if (res.ok) {
            const cfg = await res.json();
            // Ignition keys are like "DeployAll#UniversityRegistry"
            const reg = cfg['DeployAll#UniversityRegistry'];
            const sch = cfg['DeployAll#CredentialSchema'];
            if (reg) $('registry-addr').value = reg;
            if (sch) $('schema-addr').value = sch;
            console.log('✓ Loaded addresses from Ignition deployed_addresses.json');
            toast('Contract addresses loaded from Ignition deployment', 'success');
            return;
        }
    } catch { /* not available */ }

    // Source 2: deploy-config.json (written by scripts/deploy-and-save.js)
    try {
        const res = await fetch('./deploy-config.json');
        if (!res.ok) return;
        const cfg = await res.json();
        if (cfg.UniversityRegistry) $('registry-addr').value = cfg.UniversityRegistry;
        if (cfg.CredentialSchema) $('schema-addr').value = cfg.CredentialSchema;
        console.log('✓ Loaded addresses from deploy-config.json');
        toast('Contract addresses loaded from deploy-config.json', 'info');
    } catch {
        // No config found — user fills in manually
    }
}

// ── Account / network change handlers ──────────────────────────────────

function initEventListeners() {
    if (!window.ethereum) return;

    window.ethereum.on('accountsChanged', async (accounts) => {
        if (accounts.length === 0) {
            location.reload();
        } else {
            state.account = accounts[0];
            state.signer = await state.provider.getSigner();
            $('wallet-addr').textContent = shortAddr(state.account);
            if (state.registry) {
                state.isOwner = state.account.toLowerCase() === state.owner?.toLowerCase();
                state.isUni = await state.registryRead.isAuthorizedUniversity(state.account);
                // Rebuild write contracts with new signer
                state.registry = new ethers.Contract($('registry-addr').value.trim(), REGISTRY_ABI, state.signer);
                state.schema = new ethers.Contract($('schema-addr').value.trim(), SCHEMA_ABI, state.signer);
                updateRoleBadge();
                await refreshAll();
            }
            toast('Switched account: ' + shortAddr(state.account), 'info');
        }
    });

    window.ethereum.on('chainChanged', () => location.reload());
}

// ── Bootup ──────────────────────────────────────────────────────────────

window.addEventListener('DOMContentLoaded', async () => {
    initTabs();
    initEventListeners();
    await tryLoadConfig();

    // Connect button in navbar
    $('connect-btn').onclick = connectWallet;

    // Connect button on welcome card
    $('connect-prompt-btn').onclick = connectWallet;

    // Load contracts button
    $('btn-load-contracts').onclick = async () => {
        if (!state.signer) {
            await connectWallet();
            if (!state.signer) return;
        }
        await tryLoadContracts();
    };

    // Form actions
    $('btn-authorize').onclick = authorizeUniversity;
    $('btn-create-schema').onclick = createSchema;
    $('btn-refresh-unis').onclick = refreshUniversities;
    $('btn-refresh-schemas').onclick = refreshSchemas;

    // Enter key support
    const addSubmitOnEnter = (ids, fn) => ids.forEach(id => {
        $(id)?.addEventListener('keydown', e => { if (e.key === 'Enter') fn(); });
    });
    addSubmitOnEnter(['auth-addr', 'auth-name'], authorizeUniversity);
    addSubmitOnEnter(['schema-name', 'schema-code'], createSchema);
});
